#port server
port: 25565
#path to img server
# is String
imgPath: null
# max players in proxy
maxplayers: 10
# Message when the proxy is closed
shutdownMessage: "Proxy Closed"

# Downstream server (bedrock)
bedrockAddress: "join.examplemc.xyz"
bedrockPort: 10171