name: CIApp
on: [push, pull_request]
jobs:
  buildApp:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    strategy:
      matrix:
        java: [ '8' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build Compiler with Maven
        run: mvn -B package --file CraftJ2MEApp/compiler/pom.xml
      - name: Build CraftJ2ME with J2MEcompiler
        run: |-
          java -jar compiler/target/j2mecompiler-1.0-SNAPSHOT.jar
        working-directory: ./CraftJ2MEApp
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CraftJ2MEApp
          path: CraftJ2MEApp/CraftJ2ME.jar
  buildProxy:
      runs-on: ubuntu-latest
      needs: buildApp
      if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
      strategy:
        matrix:
          java: [ '17' ]
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK ${{ matrix.java }}
          uses: actions/setup-java@v4
          with:
            java-version: ${{ matrix.java }}
            distribution: 'temurin'
        - name: Build with Maven
          run: mvn -B package --file CraftJ2MEProxy/pom.xml
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: CraftJ2MEProxy
            path: CraftJ2MEProxy/target/CraftJ2ME-Proxy-1.0.0-beta.jar